esphome:
  name: anesp
  friendly_name: anesp

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:

ota:
  safe_mode: true

captive_portal:

web_server:
  port: 80
  
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

  - source:
      type: git
      url: https://github.com/pipacsba/esphome_ht16K33v110.git
    refresh: 1days

# Example configuration entry
display:
  - platform: ht16k33v110
    id: ht16k33v110_display
    address: 0x70
    inverted: false
    lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H:%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());
    intensity_source_id: display_intensity

number:
  - platform: template
    name: "Display Intensity"
    id: display_intensity
    min_value: 0
    max_value: 15
    step: 1
    optimistic: True

