esphome:
  name: livingroom-clock
  friendly_name: livingroom-clock

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:

ota:
  safe_mode: true

captive_portal:

web_server:
  port: 80
  
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: 192.168.17.208
      gateway: 192.168.17.1
      subnet: 255.255.255.0
      dns1: 192.168.17.1
  - ssid: !secret wifi_ssid_backup
    password: !secret wifi_password
    manual_ip:
      static_ip: 192.168.17.208
      gateway: 192.168.17.1
      subnet: 255.255.255.0
      dns1: 192.168.17.1
  ap:
    ssid: "LivingroomClock_Fallback"
    password: !secret wifi_password
  domain: .lan

debug:
  update_interval: 60s
# Logger must be at least debug (default)
logger:
  level: debug
  tx_buffer_size: 128
  logs:
    sensor: warn
    time: warn
    wifi: warn
    wifi_signal.sensor: warn
    text_sensor: warn
    internal_temperature: warn

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

external_components:
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_VEML7700.git
    #refresh: 1min
    refresh: 1days
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_ht16K33v110.git
    refresh: 1min

# Example configuration entry
display:
    platform: ht16k33v110
    id: ht16k33v110_display
    address: 0x70
    inverted: false
    lambda: |-
      it.print("0123");
    intensity_map:
       source_id: livingRoomClock_light
       map:
          10 -> 1
          30 -> 2
          90 -> 3
          270 -> 4
          350 -> 5
          800 -> 6
          1000 -> 13
          2000 -> 15   

sensor:
  - platform: veml7700
    name: "LivingRoomClock_light"
    id: livingRoomClock_light
    address: 0x10
    update_interval: 60s
    force_update: True
    gain: "2x"
    integration_time: 100ms
    psm: 1




